### ISSUE TITLE
Bug Report: Incompatible transformers requirements block ComfyUI-nunchaku

### ISSUE THREAD

**Issue by IL3DCR** [nunchaku-ai/ComfyUI-nunchaku#617]
Environment

OS: Windows 10 / 11

Python: 3.12.9

Torch: 2.7.0+cu128

GPU: NVIDIA RTX 3060 Ti

ComfyUI: 0.3.60 (Electron build)

ComfyUI-nunchaku: 1.0.1

Nunchaku wheel: nunchaku-1.0.0+torch2.7-cp312-cp312-win_amd64.whl

What happened

After successfully installing the correct wheel (nunchaku 1.0.0), ComfyUI-nunchaku fails to load due to a dependency conflict between diffusers, transformers, and other installed packages.

Log excerpt

Nunchaku version: 1.0.0
ComfyUI-nunchaku version: 1.0.1

RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of:
cannot import name 'FLAX_WEIGHTS_NAME' from 'transformers.utils'

When trying to resolve manually:

nunchaku 1.0.0 requires diffusers >= 0.35.1 and transformers >= 4.53.3.

vibevoice 0.0.1 requires transformers == 4.51.3 and accelerate == 1.6.0.

Installing transformers >= 4.53.3 → breaks VibeVoice.

Installing transformers == 4.44.2 (to restore FLAX_WEIGHTS_NAME) → breaks Nunchaku (requires 4.53.3+).

This creates an unsolvable dependency conflict in a single environment.

What I expected

ComfyUI-nunchaku to work with Nunchaku 1.0.0 and allow Qwen-Edit nodes to load without breaking other custom nodes.

What actually happens

With the current requirements:

If I satisfy Nunchaku (transformers >= 4.53.3) → the import error occurs (FLAX_WEIGHTS_NAME removed in newer versions).

If I roll back transformers to <= 4.44.2 → Nunchaku refuses to load (requires >= 4.53.3).

VibeVoice and other extensions that depend on transformers <= 4.51.3 cannot coexist with Nunchaku 1.0.0.

Possible solutions

Relax Nunchaku’s strict dependency (transformers >= 4.53.3) to allow compatibility with 4.44.x (still includes FLAX_WEIGHTS_NAME).

Patch diffusers/Nunchaku to remove reliance on the deprecated constant.

Provide guidance for running Nunchaku in a separate venv if strict isolation is required.

Summary

At the moment, ComfyUI-nunchaku 1.0.1 + Nunchaku 1.0.0 cannot be used in environments where other nodes require transformers <= 4.51.3.
This blocks usage of Qwen-Edit and other features in a shared ComfyUI setup.

**Comment by lmxyy** [comment]
You can try transformers 4.51.3. Hopefully it can work. I just lock transformer to a decent version and haven't not test the older version.
