### ISSUE TITLE
[Bug] Node `NunchakuFluxDiTLoader` import failed

### ISSUE THREAD

**Issue by mholtgraewe** [nunchaku-ai/ComfyUI-nunchaku#746]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/nunchaku-tech/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [ ] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [ ] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/nunchaku-tech/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. I will do my best to describe the issue in English.

### Describe the Bug

After updating both Nunchaku and ComfyUI-nunchaku to v1.1.0, the ComfyUI plugin fails to load.

Nunchaku version: 1.1.0
ComfyUI-nunchaku version: 1.1.0
Node `NunchakuFluxDiTLoader` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 82, in <module>
    from .nodes.models.flux import NunchakuFluxDiTLoader
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/flux.py", line 16, in <module>
    from nunchaku import NunchakuFluxTransformer2dModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Node `NunchakuQwenImageDiTLoader` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 89, in <module>
    from .nodes.models.qwenimage import NunchakuQwenImageDiTLoader
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/qwenimage.py", line 15, in <module>
    from ...model_configs.qwenimage import NunchakuQwenImage
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/model_configs/qwenimage.py", line 8, in <module>
    from .. import model_base
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/model_base/__init__.py", line 1, in <module>
    from .qwenimage import NunchakuQwenImage
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/model_base/qwenimage.py", line 10, in <module>
    from nunchaku.models.linear import SVDQW4A4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Nodes `NunchakuFluxLoraLoader` and `NunchakuFluxLoraStack` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 96, in <module>
    from .nodes.lora.flux import NunchakuFluxLoraLoader, NunchakuFluxLoraStack
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/lora/flux.py", line 9, in <module>
    from nunchaku.lora.flux import to_diffusers
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Nodes `NunchakuTextEncoderLoader` and `NunchakuTextEncoderLoaderV2` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 104, in <module>
    from .nodes.models.text_encoder import NunchakuTextEncoderLoader, NunchakuTextEncoderLoaderV2
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/text_encoder.py", line 18, in <module>
    from nunchaku import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Nodes `NunchakuPulidApply`,`NunchakuPulidLoader`, `NunchakuPuLIDLoaderV2` and `NunchakuFluxPuLIDApplyV2` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 119, in <module>
    from .nodes.models.pulid import (
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/pulid.py", line 19, in <module>
    from nunchaku.models.pulid.pulid_forward import pulid_forward
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Nodes `NunchakuFluxIPAdapterApply` and `NunchakuIPAdapterLoader` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 136, in <module>
    from .nodes.models.ipadapter import NunchakuFluxIPAdapterApply, NunchakuIPAdapterLoader
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/ipadapter.py", line 14, in <module>
    from nunchaku.models.ip_adapter.diffusers_adapters import apply_IPA_on_pipe
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Nodes `NunchakuZImageDiTLoader` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 144, in <module>
    from .nodes.models.zimage import NunchakuZImageDiTLoader
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/zimage.py", line 12, in <module>
    from nunchaku.models.transformers.utils import patch_scale_key
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
Node `NunchakuModelMerger` import failed:
Traceback (most recent call last):
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/__init__.py", line 151, in <module>
    from .nodes.tools.merge_safetensors import NunchakuModelMerger
  File "/[path]/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/tools/merge_safetensors.py", line 10, in <module>
    from nunchaku.merge_safetensors import merge_safetensors
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/__init__.py", line 1, in <module>
    from .models import (
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/__init__.py", line 1, in <module>
    from .text_encoders.t5_encoder import NunchakuT5EncoderModel
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/t5_encoder.py", line 18, in <module>
    from .linear import W4Linear
  File "/[path]/.venv/lib/python3.12/site-packages/nunchaku/models/text_encoders/linear.py", line 10, in <module>
    from ..._C.ops import gemm_awq, gemv_awq
ImportError: libcudart.so.13: cannot open shared object file: No such file or directory
'nunchaku_versions.json' not found. Node will start in minimal mode. Use 'update node' to fetch versions.

### Environment

Ubuntu 24.04.3 LTS
NVIDIA Driver Version: 580.95.05
CUDA Version: 13.0
ComfyUI Version: 1.5.3
Python 3.12.2
Nunchaku version: 1.1.0
ComfyUI-nunchaku version: 1.1.0

### Reproduction Steps

1. Update Nunchaku via Terminal:

`pip install https://github.com/nunchaku-tech/nunchaku/releases/download/v1.1.0/nunchaku-1.1.0+torch2.9-cp312-cp312-linux_x86_64.whl`

2. Use the 'Update All' button in the ComfyUI Manager

**Comment by alijazizaib** [comment]
Same issue here.

**Comment by 2600th** [comment]
Nodes `NunchakuZImageDiTLoader` import failed:
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 144, in <module>
    from .nodes.models.zimage import NunchakuZImageDiTLoader
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\zimage.py", line 12, in <module>
    from nunchaku.models.transformers.utils import patch_scale_key
ImportError: cannot import name 'patch_scale_key' from 'nunchaku.models.transformers.utils' (D:\ComfyUI\scripts\venv\Lib\site-packages\nunchaku\models\transformers\utils.py)
'nunchaku_versions.json' not found. Node will start in minimal mode. Use 'update node' to fetch versions.

**Comment by scriptr78** [comment]
After updating ComfyUI-nunchaku to v1.1.0 working only 4 nodes:
1. Nunchaku Installer
2. FLUX Depth Preprocessor (Deprecated)
3. Nunchaku Qwen-Image DiT Loader
4. Nunchaku Z-Image DiT Loader
Other nodes looking as not installed

======================================== ComfyUI-nunchaku Initialization ========================================
Nunchaku version: Unknown version
ComfyUI-nunchaku version: 1.1.0
Could not parse nunchaku version: Unknown version. Please ensure you have at least v1.0.0.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Node `NunchakuFluxDiTLoader` import failed:
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 82, in <module>
    from .nodes.models.flux import NunchakuFluxDiTLoader
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\flux.py", line 16, in <module>
    from nunchaku import NunchakuFluxTransformer2dModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\__init__.py", line 1, in <module>
    from .models import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\__init__.py", line 2, in <module>
    from .transformers import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\__init__.py", line 5, in <module>
    from .transformer_zimage import NunchakuZImageTransformer2DModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\transformer_zimage.py", line 13, in <module>
    from diffusers.models.transformers.transformer_z_image import FeedForward as ZImageFeedForward
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_z_image'
Nodes `NunchakuFluxLoraLoader` and `NunchakuFluxLoraStack` import failed:
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 96, in <module>
    from .nodes.lora.flux import NunchakuFluxLoraLoader, NunchakuFluxLoraStack
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\lora\flux.py", line 11, in <module>
    from ...wrappers.flux import ComfyFluxWrapper, copy_with_ctx
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\wrappers\flux.py", line 15, in <module>
    from nunchaku import NunchakuFluxTransformer2dModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\__init__.py", line 1, in <module>
    from .models import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\__init__.py", line 2, in <module>
    from .transformers import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\__init__.py", line 5, in <module>
    from .transformer_zimage import NunchakuZImageTransformer2DModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\transformer_zimage.py", line 13, in <module>
    from diffusers.models.transformers.transformer_z_image import FeedForward as ZImageFeedForward
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_z_image'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
Nodes `NunchakuTextEncoderLoader` and `NunchakuTextEncoderLoaderV2` import failed:
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 104, in <module>
    from .nodes.models.text_encoder import NunchakuTextEncoderLoader, NunchakuTextEncoderLoaderV2
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\text_encoder.py", line 18, in <module>
    from nunchaku import NunchakuT5EncoderModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\__init__.py", line 1, in <module>
    from .models import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\__init__.py", line 2, in <module>
    from .transformers import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\__init__.py", line 5, in <module>
    from .transformer_zimage import NunchakuZImageTransformer2DModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\transformer_zimage.py", line 13, in <module>
    from diffusers.models.transformers.transformer_z_image import FeedForward as ZImageFeedForward
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_z_image'
Nodes `NunchakuPulidApply`,`NunchakuPulidLoader`, `NunchakuPuLIDLoaderV2` and `NunchakuFluxPuLIDApplyV2` import failed:
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 119, in <module>
    from .nodes.models.pulid import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\pulid.py", line 19, in <module>
    from nunchaku.models.pulid.pulid_forward import pulid_forward
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\__init__.py", line 1, in <module>
    from .models import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\__init__.py", line 2, in <module>
    from .transformers import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\__init__.py", line 5, in <module>
    from .transformer_zimage import NunchakuZImageTransformer2DModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\transformer_zimage.py", line 13, in <module>
    from diffusers.models.transformers.transformer_z_image import FeedForward as ZImageFeedForward
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_z_image'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Nodes `NunchakuFluxIPAdapterApply` and `NunchakuIPAdapterLoader` import failed:
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 136, in <module>
    from .nodes.models.ipadapter import NunchakuFluxIPAdapterApply, NunchakuIPAdapterLoader
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\models\ipadapter.py", line 14, in <module>
    from nunchaku.models.ip_adapter.diffusers_adapters import apply_IPA_on_pipe
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\__init__.py", line 1, in <module>
    from .models import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\__init__.py", line 2, in <module>
    from .transformers import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\__init__.py", line 5, in <module>
    from .transformer_zimage import NunchakuZImageTransformer2DModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\transformer_zimage.py", line 13, in <module>
    from diffusers.models.transformers.transformer_z_image import FeedForward as ZImageFeedForward
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_z_image'
Node `NunchakuModelMerger` import failed:
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\__init__.py", line 151, in <module>
    from .nodes.tools.merge_safetensors import NunchakuModelMerger
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-nunchaku\nodes\tools\merge_safetensors.py", line 10, in <module>
    from nunchaku.merge_safetensors import merge_safetensors
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\__init__.py", line 1, in <module>
    from .models import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\__init__.py", line 2, in <module>
    from .transformers import (
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\__init__.py", line 5, in <module>
    from .transformer_zimage import NunchakuZImageTransformer2DModel
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\nunchaku\models\transformers\transformer_zimage.py", line 13, in <module>
    from diffusers.models.transformers.transformer_z_image import FeedForward as ZImageFeedForward
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_z_image'
=================================================================================================================

**Comment by shiguanggougouo** [comment]
This video can solve this problem and has been tested to be effective：https://youtu.be/RFvufp4LNrU

It's a Chinese tutorial. You can jump to nunchaku to see the steps

**Comment by 2600th** [comment]
Following this video: https://youtu.be/RFvufp4LNrU

Go to line 12 (approximately) and delete or comment out this line:

```
# Change this:
from nunchaku.models.transformers.utils import patch_scale_key

# To this:
# from nunchaku.models.transformers.utils import patch_scale_key
```

Scroll down to the _load function (around line 134 in your provided file). You will see a call to patch_scale_key. You must delete or comment out this line as well.

```
model_config.set_inference_dtype(unet_dtype, manual_cast_dtype)
model = model_config.get_model(patched_sd, "")

# Change this:
patch_scale_key(model.diffusion_model, patched_sd)

# To this:
# patch_scale_key(model.diffusion_model, patched_sd)

model.load_model_weights(patched_sd, "")
return ModelPatcher(model, load_device=load_device, offload_device=offload_device)
```

**It did resolve node not loading error. But now getting images like this:**

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/3372d22d-74f8-400b-ac5e-29f1d527437d" />

**Comment by shiguanggougouo** [comment]
非50系列显卡已经成功了。对于50系列显卡，需要把pytorch版本升到了2.9以上，接着下载最新的双节棍轮子，然后把xformers（会报错版本没更新）换成使用Sage Attention

**Comment by shiguanggougouo** [comment]
我用的是秋叶的绘世启动器，在高级选项-高级选项-性能设置-交叉注意力优化方案里，改为使用sege注意力。如果还是失败，改为sdp方案

![Image](https://github.com/user-attachments/assets/9e55bbfa-6cdd-4a44-8d54-24375f915528)

**Comment by mholtgraewe** [comment]
Reinstalling PyTorch using the wheel for Cuda 13.0 fixed the issue:

`pip install --force-reinstall torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu130`

**Comment by syguan96** [comment]
If I still use cuda 12.8, how to solve this problem?

**Comment by mholtgraewe** [comment]
> If I still use cuda 12.8, how to solve this problem?

I think you need to upgrade to CUDA 13.0.

**Comment by Vaizarr** [comment]
I had the same issues, upgrading to CUDA 13.0 did not solve it for me. It did cause some conflict with 'numba' because it also updated 'numpy'. `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. numba 0.63.1 requires numpy<2.4,>=1.22, but you have numpy 2.4.1 which is incompatible.` 

Nunchaku needs >=2.0 so  `pip install "numpy>=2.0,<2.3"` solved that.

I tried installing the Nunchaku wheels hoping if I could then upgrade to 1.20 but that didn't work either (NULL error on latest release?) after adding the version list .json manually and clicking multiple times it reported success but still wouldn't install the module, I then also noticed new dll load errors in the startup log. (ImportError: DLL load failed while importing _C: The specified procedure could not be found.)

Now I'm on PyTorch 2.10 which also has no wheel I think(?), but was out of patience so pip uninstall Nunchaku and ran the torch 2.11 install under 2.10 anyways, which worked perfect, no more errors.

`.\venv\Scripts\python.exe -m pip uninstall nunchaku
.\venv\Scripts\python.exe -m pip install https://github.com/Nunchaku-AI/nunchaku/releases/download/v1.2.0/nunchaku-1.2.0+torch2.11-cp312-cp312-win_amd64.whl`


(To anyone stumbling upon this, do check this first - https://nunchaku.tech/docs/nunchaku/installation/installation.html )
